"""Cleaned out unused data members

Revision ID: 27e3faaf3f2c
Revises: 
Create Date: 2018-10-10 12:39:39.015972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27e3faaf3f2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('director',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_director_name'), 'director', ['name'], unique=False)
    op.create_table('gross',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gross_total'), 'gross', ['total'], unique=False)
    op.create_table('stars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stars_name'), 'stars', ['name'], unique=False)
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('genre', sa.String(length=64), nullable=True),
    sa.Column('date', sa.String(length=64), nullable=True),
    sa.Column('synopsis', sa.String(length=500), nullable=True),
    sa.Column('director_id', sa.Integer(), nullable=True),
    sa.Column('gross_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['director_id'], ['director.id'], ),
    sa.ForeignKeyConstraint(['gross_id'], ['gross.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_date'), 'movie', ['date'], unique=False)
    op.create_index(op.f('ix_movie_genre'), 'movie', ['genre'], unique=False)
    op.create_index(op.f('ix_movie_synopsis'), 'movie', ['synopsis'], unique=False)
    op.create_index(op.f('ix_movie_title'), 'movie', ['title'], unique=False)
    op.create_table('movie_to_stars',
    sa.Column('movieID', sa.Integer(), nullable=False),
    sa.Column('starsID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movieID'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['starsID'], ['stars.id'], ),
    sa.PrimaryKeyConstraint('movieID', 'starsID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_to_stars')
    op.drop_index(op.f('ix_movie_title'), table_name='movie')
    op.drop_index(op.f('ix_movie_synopsis'), table_name='movie')
    op.drop_index(op.f('ix_movie_genre'), table_name='movie')
    op.drop_index(op.f('ix_movie_date'), table_name='movie')
    op.drop_table('movie')
    op.drop_index(op.f('ix_stars_name'), table_name='stars')
    op.drop_table('stars')
    op.drop_index(op.f('ix_gross_total'), table_name='gross')
    op.drop_table('gross')
    op.drop_index(op.f('ix_director_name'), table_name='director')
    op.drop_table('director')
    # ### end Alembic commands ###
